### ISSUE TITLE
Clarification Needed: Which Binary to Flash on the Device?

### ISSUE THREAD

**Issue by logkos** [svoboda18/lk#2]
first of all thx for sharing these!
I've built this for my mt6739 device and multiple files came out as a result. Which one of these should be impacted to device?

and can I use dtb image extracted from stock android kernel?
![image](https://github.com/user-attachments/assets/81881e67-8c22-40a7-85f6-4137a9608160)

**Comment by svoboda18** [comment]
Hello,

I will assume that you have already added your specific device's drivers and made all the necessary changes.

I usually just flash the `lk-dtb.img` using SPFT, if your device does not use signing, also you must replace [main_dtb_header.bin](https://github.com/svoboda18/lk/blob/main/main_dtb_header.bin) with your own either extracted from stock lk or from boot image.

if your device does use signing, you must have an unlocked bootloader, then there's two options either with a custom recovery, to able to flash the custom `lk` or you make your own `preloader` with disabled secure download.

there is also a case where will be forced to go through the second option, it is when secure boot is also enabled, which means un-signed `lk` will not boot.
